### PR TITLE
Removed the awful alert when the screenlog miss

### PR DESCRIPTION
**Pull request by Pandry**

### CODE REVIEW

**Comment by Pandry** [comment]
#900

**Comment by Pandry** [comment]
@ulrichblock Do you like this?
Why does all the pull request were merged except for this one?

**Comment by ulrichblock** [comment]
Because I do not think the standard alter is that awful. Plus I do not like the hack you have done.

**Comment by Pandry** [comment]
Yeah, but some users complained about the alert that every 3 seconds pops up again (so some of them can't even close the page) and it could be annoying...

**Pull request closed without merging**
